---
# tasks file for app-todo
- name: install other dependencies required by the application
  package:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - unzip
    - npm
- name: create directory for app
  file:
    path: "{{ app_dir }}"
    state: directory
    recurse: true
- name: Unpack the application code
  unarchive:
    src: app.zip
    dest: "{{ app_dir }}"
- name: Create application db config
  template:
    src: mysql.js.j2
    dest: "{{ app_dir }}/app/src/persistence/mysql.js"
- name: Create application config
  template:
    src: index.js.j2
    dest: "{{ app_dir }}/app/src/index.js"
- name:  dependencies
  npm:
     path: "{{ app_dir }}/app"
- name: Start the application
  command:
    chdir: "{{ app_dir }}/app/src/"
    cmd: "node {{ app_dir}}/app/src/index.js"
  async: 1000
  poll: 0
